# Generated by Django 4.2.17 on 2025-02-06 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resumes', '0004_alter_resume_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='data',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resumes.resumetemplate'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
