# Generated by Django 4.2.17 on 2025-02-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_alter_resume_data_alter_resume_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeorder',
            name='ordered_sections',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='resumeorder',
            name='font_color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='resumeorder',
            name='font_family',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resumeorder',
            name='font_size',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='resumeorder',
            name='font_weight',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='resumeorder',
            name='section_alignment',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='resumeorder',
            name='section_spacing',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
