# Generated by Django 4.2.17 on 2025-02-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0007_resumeorder_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeorder',
            name='background_color',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
