# Generated by Django 4.2.17 on 2025-02-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0008_alter_resumeorder_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeorder',
            name='border_style',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='resumeorder',
            name='font_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='resumeorder',
            name='font_family',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumeorder',
            name='font_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='resumeorder',
            name='font_style',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='resumeorder',
            name='font_weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resumeorder',
            name='section_alignment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='resumeorder',
            name='section_spacing',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
