# Generated by Django 4.2.17 on 2025-02-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0009_alter_resumeorder_border_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeorder',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumeorder',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumeorder',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
