# Generated by Django 4.2.17 on 2025-02-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0010_resumeorder_email_resumeorder_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeorder',
            name='college',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumeorder',
            name='degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumeorder',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumeorder',
            name='year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
