# Generated by Django 4.2.17 on 2025-02-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0011_resumeorder_college_resumeorder_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeorder',
            name='projects',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
