# Generated by Django 4.2.17 on 2025-02-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0012_resumeorder_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeorder',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumeorder',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumeorder',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
