# Generated by Django 4.2.17 on 2025-02-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0014_resumeorder_certifications_resumeorder_interest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeorder',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resumeorder',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='resumeorder',
            name='qr_payment',
            field=models.ImageField(blank=True, null=True, upload_to='payments/'),
        ),
    ]
