# Generated by Django 4.2.17 on 2025-02-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0015_resumeorder_is_approved_resumeorder_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeorder',
            name='qr_payment',
            field=models.FileField(blank=True, null=True, upload_to='qr_payments/'),
        ),
    ]
