# Generated by Django 4.2.17 on 2025-02-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0016_alter_resumeorder_qr_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeorder',
            name='qr_payment',
        ),
        migrations.AddField(
            model_name='resumeorder',
            name='qr_payment_new',
            field=models.FileField(blank=True, null=True, upload_to='payments/'),
        ),
    ]
