# Generated by Django 4.2.17 on 2025-02-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0017_remove_resumeorder_qr_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeorder',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='orders/qr_codes/'),
        ),
    ]
