# Generated by Django 4.2.17 on 2025-02-07 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0018_resumeorder_qr_code_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumeorder',
            old_name='qr_payment_new',
            new_name='qr_payment',
        ),
    ]
