# Generated by Django 4.2.17 on 2025-02-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0019_rename_qr_payment_new_resumeorder_qr_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeorder',
            name='professional_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
