# Generated by Django 4.2.17 on 2025-02-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0020_resumeorder_professional_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeorder',
            name='education',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
