# Generated by Django 4.2.17 on 2025-02-09 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0023_uploadedresume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedResume',
        ),
    ]
