# Generated by Django 4.2.17 on 2025-02-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0025_remove_resumeorder_ordered_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumetemplate',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
